### PR TITLE
Fix wrong package name test

### LINKED ISSUE #31: failing unit test
http://jenkins.ros.org/job/devel-indigo-pluginlib/11/
http://jenkins.ros.org/job/devel-jade-pluginlib/3/

### PR DESCRIPTION
**Pull request by esteve**
Throw an exception if ClassLoader can't be instantiated due to an invalid package name

Fixes #31

### CODE REVIEW

File: include/pluginlib/class_loader_imp.h [hunk 1]
```diff
@@ -59,6 +59,11 @@ namespace pluginlib
   /***************************************************************************/
   {
     ROS_DEBUG_NAMED("pluginlib.ClassLoader","Creating ClassLoader, base = %s, address = %p", base_class.c_str(), this);
+    if (ros::package::getPath(package).empty())
```
Comment (dirk-thomas) [inline include/pluginlib/class_loader_imp.h]: Use `package_` instead of `package` as in the rest of the function body?

File: include/pluginlib/class_loader_imp.h [hunk 2]
```diff
@@ -59,6 +59,11 @@ namespace pluginlib
...
+    {
+      throw pluginlib::ClassLoaderException("Unable to find package: " + package_);
```
Comment (dirk-thomas) [inline include/pluginlib/class_loader_imp.h:64]: The docblock needs to be updated for that.

File: include/pluginlib/class_loader_imp.h (hunk 1 above)
Comment (esteve) [inline include/pluginlib/class_loader_imp.h]: Fixed.

File: include/pluginlib/class_loader_imp.h (hunk 2 above)
Comment (esteve) [inline include/pluginlib/class_loader_imp.h:64]: Fixed.

**Comment by dirk-thomas** [comment]
lgtm

**Comment by dirk-thomas** [comment]
Does this rely on the change in rospack? If yes, this package needs to depend on the upcoming rospack version.

**Comment by esteve** [comment]
It does not depend on https://github.com/ros/rospack/pull/51, the rospack PR is just a behavior we found out, but it's independent from this.
